### ISSUE TITLE
TypeError: int() argument must be a string or a number, not 'NoneType'

### ISSUE THREAD

**Issue by Lange** [jay0lee/chrome-bisect#2]
Hello!

I get this error for most values of "last version of Chrome":

```
C:\Program Files (x86)\ChromeBisect>chrome-bisect.exe
logging to stdout and c:\users\vanca\appdata\local\temp\chrome-bisect-2019-01-30-19-32-20-8320009jens5.log
Enter website used to start issue reproduction: http://localhost/redacted.html
Got Chromium args: ['--no-first-run', 'http://localhost/redacted.html']
Running on Windows
64-bit
Running the win64 builds
Enter the last version of Chrome where you DID NOT see this issue: 69
Enter the first version of Chrome where you DID see this issue: 71
finding exact Chromium branch for 69...
Chrome 69 == Chromium branch 69.0.3497.0
Traceback (most recent call last):
  File "chrome-bisect.py", line 1306, in <module>
  File "chrome-bisect.py", line 1233, in main
  File "chrome-bisect.py", line 1049, in convertChromeVersionToBuild
TypeError: int() argument must be a string or a number, not 'NoneType'
[42472] Failed to execute script chrome-bisect
```

On the cases where I get past that, it will error like this when trying to download the next revision:
```
C:\Program Files (x86)\ChromeBisect>chrome-bisect.exe
logging to stdout and c:\users\vanca\appdata\local\temp\chrome-bisect-2019-01-30-19-27-41-7680007odtrf.log
Enter website used to start issue reproduction: http://localhost/redacted.html
Got Chromium args: ['--no-first-run', 'http://localhost/redacted.html']
Running on Windows
64-bit
Running the win64 builds
Enter the last version of Chrome where you DID NOT see this issue: 65
Enter the first version of Chrome where you DID see this issue: 71
finding exact Chromium branch for 65...
Chrome 65 == Chromium branch 65.0.3325.0
Chrome version 65.0.3325.0 == Chromium build 530369
Chrome 71 == Chromium branch 71.0.3578.0
Chrome version 71.0.3578.0 == Chromium build 599034
Downloading list of known revisions...
Loaded revisions 389148-627698 from C:\Program Files (x86)\ChromeBisect\.chrome-bisect-cache.json
Downloading revision 530373...
Trying revision 530373 at 2019-01-30 19:28:55.479000...
Revision 530373 is [(g)ood/(b)ad/(r)etry/(u)nknown/(s)tdout/(q)uit]: g
Downloading revision 598932...
Trying revision 598932 at 2019-01-30 19:29:10.185000...
File is not a zip file
Traceback (most recent call last):
  File "chrome-bisect.py", line 1306, in <module>
  File "chrome-bisect.py", line 1267, in main
  File "chrome-bisect.py", line 802, in Bisect
  File "chrome-bisect.py", line 721, in VerifyEndpoint
UnboundLocalError: local variable 'exit_status' referenced before assignment
[17248] Failed to execute script chrome-bisect
```

**Comment by laza-github** [comment]
this has been fixed with https://github.com/jay0lee/chrome-bisect/commit/82a3003878d20bd7b3f5a292ca90cb18098257ab

**Comment by Lange** [comment]
It looks like this is unfortunately not fixed, just tried with the newly released v1.05:

```
C:\Program Files (x86)\ChromeBisect>chrome-bisect.exe
logging to stdout and c:\users\vanca\appdata\local\temp\chrome-bisect-2019-04-12-23-04-35-009000koxm1z.log
Enter website used to start issue reproduction: http://localhost:9090/REDACTED.html
Got Chromium args: ['--no-first-run', 'http://localhost:9090/REDACTED.html']
Running on Windows
64-bit
Running the win64 builds
Enter the last version of Chrome where you DID NOT see this issue: 60
Enter the first version of Chrome where you DID see this issue: 71
finding exact Chromium branch for 60...
Chrome 60 == Chromium branch 60.0.3112.0
Traceback (most recent call last):
  File "chrome-bisect.py", line 1347, in <module>
  File "chrome-bisect.py", line 1266, in main
  File "chrome-bisect.py", line 1075, in convertChromeVersionToBuild
TypeError: int() argument must be a string or a number, not 'NoneType'
[48384] Failed to execute script chrome-bisect

C:\Program Files (x86)\ChromeBisect>chrome-bisect.exe --version
Chrome Bisect 1.05
```

cc: @jay0lee

**Comment by jay0lee** [comment]
So the challenge here is that we depend on the URL:

https://omahaproxy.appspot.com/deps.json?version=<Chrome version number>

to convert something like 60.0.3112.0 to a Chromium build number which is what we need to download the build. This generally works on most versions but some versions seem to not return anything useful here.

1.06 will iterate over the patch version, usually it can eventually find the right patch version to get the build number but you might also try specifying real, full Chrome versions. For example, 60.0.3112.78, the first stable 60 Chrome release found exact number by googling "chrome 60 stable release".

**Comment by Lange** [comment]
It works! Thank you so much for this tool, it really is a joy to use 😄
